image: 'node:18-alpine'

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - node_modules

stages:
  - prepare
  - test
  - build
  - deploy

npm-install:
  stage: prepare
  script:
    - npm install

prettier:
  stage: prepare
  needs: [npm-install]
  script:
    - npm run prettier

eslint:
  stage: prepare
  needs: [npm-install]
  script:
    - npm run eslint

build:
  stage: build
  needs: [npm-install]
  variables:
    NODE_ENV: production
    OUTPUT_DIR: dist
  script:
    - npm run build
    - test -e $OUTPUT_DIR
  artifacts:
    expire_in: 1w
    paths:
      - $OUTPUT_DIR
      - sourcemap

deploy-staging:
  stage: deploy
  needs: [build]
  dependencies: [build]
  variables:
    NODE_ENV: production
    FLY_ACCESS_TOKEN: $FLY_ACCESS_TOKEN
  script:
    - apk --no-cache add curl
    - curl -L https://fly.io/install.sh | sh
    - ~/.fly/bin/flyctl deploy -c fly.toml
  only:
    - deploy-staging
